version: 2.1

# version: 2 
jobs:
  build:  
    docker: 
      - image: circleciomf/ruby_2_5_1-java_8-node_6_6-browsers

    
    steps:
    
      - checkout
      
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - snyk/monitor
orbs:
  snyk: snyk/snyk@0.0.10
  
#       - run: bash <(curl -s https://scripts.scantist.com/ci-circle.sh)
